version: "3.3"

services:
  app:
    build: "."
    container_name: sample_backend
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:mySecretPassword@db:5432/init
    depends_on:
      - db

  db:
    image: postgres
    container_name: postgresdb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: mySecretPassword
      POSTGRES_USE: postgres
      POSTGRES_DB: init
 

volumes:
  postgres_data:
