version: "2.4"

services:
  app:
    build: "."
    container_name: sample_backend
    ports:
      - '3000:3000'
    environment:
      - DATABASE_URL=postgresql://postgres:mySecretPassword@db:5432/init
    depends_on:
      db : 
        condition: service_healthy

  db:
    image: postgres
    container_name: postgresdb
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql@16/data
    environment:
      POSTGRES_PASSWORD: mySecretPassword
      POSTGRES_USER: postgres
      POSTGRES_DB: init
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}' ]
      interval: 5s
      timeout: 5s
      retries: 5
 

volumes:
  postgres_data:
